version: '3'
services:
  web:
    build:
      context: ./docker/web
      dockerfile: Dockerfile
    ports:
      - 8095:80
    volumes:
      - ./:/var/www/app

  db:
    image: mysql
    tty: true
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: docker-db
      MYSQL_USER: docker-user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 33062:3306

  composer:
    image: composer:latest
    volumes:
      - ./:/app
    environment:
      COMPOSER_MEMORY_LIMIT: -1

  node:
    image: node:12
    working_dir: /app
    volumes:
      - .:/app
